//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace printPoster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("printPoster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutFmt {
            get {
                return ResourceManager.GetString("AboutFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file.
        /// </summary>
        internal static string ErrorOpening {
            get {
                return ResourceManager.GetString("ErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing dpi.
        /// </summary>
        internal static string ErrorParsingDpi {
            get {
                return ResourceManager.GetString("ErrorParsingDpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing overlap.
        /// </summary>
        internal static string ErrorParsingOverlap {
            get {
                return ResourceManager.GetString("ErrorParsingOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is corrupt or not an image one..
        /// </summary>
        internal static string FileCorruptFmt {
            get {
                return ResourceManager.GetString("FileCorruptFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files|*.jpg;*.jpeg;*.png;*.gif;*.tiff;*.tif;*.bmp|All files|*.*.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon2 {
            get {
                object obj = ResourceManager.GetObject("icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid overlap.
        /// </summary>
        internal static string InvalidOverlap {
            get {
                return ResourceManager.GetString("InvalidOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (native).
        /// </summary>
        internal static string NativeMark {
            get {
                return ResourceManager.GetString("NativeMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a float value.
        /// </summary>
        internal static string NotAFloatFmt {
            get {
                return ResourceManager.GetString("NotAFloatFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlap was adjusted to fit page size..
        /// </summary>
        internal static string OverlapAdjusted {
            get {
                return ResourceManager.GetString("OverlapAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlap (mm):.
        /// </summary>
        internal static string OverlapLbl {
            get {
                return ResourceManager.GetString("OverlapLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlap shouldn&apos;t exceed page&apos;s mimimal dimension..
        /// </summary>
        internal static string OverlapTooBig {
            get {
                return ResourceManager.GetString("OverlapTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page|pages.
        /// </summary>
        internal static string PageDeclines {
            get {
                return ResourceManager.GetString("PageDeclines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        internal static string PageFmt {
            get {
                return ResourceManager.GetString("PageFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page setup....
        /// </summary>
        internal static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print area:.
        /// </summary>
        internal static string PrintArea {
            get {
                return ResourceManager.GetString("PrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print zone: top left: {0}, {1} px, size: {2} x {3} px, {4} pages.
        /// </summary>
        internal static string PrintAreaFmt {
            get {
                return ResourceManager.GetString("PrintAreaFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to printPoster is designed for printing large images such as posters, topographic maps, banners on a set of smaller sheets, preserving desired scale. .
        /// </summary>
        internal static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection top left: {0}, {1}, size {2} x {3} px, {4}.
        /// </summary>
        internal static string SelectionFmt {
            get {
                return ResourceManager.GetString("SelectionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1} cm.
        /// </summary>
        internal static string SizeFmt {
            get {
                return ResourceManager.GetString("SizeFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionFmt {
            get {
                return ResourceManager.GetString("VersionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom: {0}%.
        /// </summary>
        internal static string ZoomFmt {
            get {
                return ResourceManager.GetString("ZoomFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom &amp;in.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom &amp;in.
        /// </summary>
        internal static string ZoomInMenu {
            get {
                return ResourceManager.GetString("ZoomInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom &amp;out.
        /// </summary>
        internal static string ZoomOutMenu {
            get {
                return ResourceManager.GetString("ZoomOutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to window.
        /// </summary>
        internal static string ZoomToWindow {
            get {
                return ResourceManager.GetString("ZoomToWindow", resourceCulture);
            }
        }
    }
}
